name: E2E Test
on: [push, pull_request]

jobs:
  e2e-test:
    name: Node.js
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: ["10.x", "12.x", "14.x"]

    steps:
      - name: Checkout https://github.com/${{ github.repository }}@${{ github.ref }}
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          persist-credentials: false

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@1a4442cacd436585916779262731d1f68e0049b1 # v3.8.2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use cache
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          path: |
            ~/.npm
            ~/.cache
          key: ${{ runner.os }}-node${{ matrix.node-version }}-E2E-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: |
          npm ci
          npm run cy:verify

      - name: Start MongoDB
        run: |
          docker run -d -p 27017:27017 mongo:4.0
          timeout 60s bash -c 'until nc -z -w 2 localhost 27017 && echo MongoDB ready; do sleep 2; done'

      - name: Run E2E test suite
        id: test-suite
        run: |
          NODE_ENV=test npm start -- --silent &
          npm run test:ci -- --config video=true

      - name: Prepare cypress artifacts
        if: failure() && (steps.test-suite.outcome == 'failure')
        working-directory: ./test/e2e
        run: >
          mkdir -p "screenshots" && find "screenshots" -mindepth 1 -maxdepth 1 -type d
          -exec sh -c 'mv -- "videos/$(basename "$1").mp4" "$1"' _ {} \;

      - name: Upload cypress artifacts
        if: failure() && (steps.test-suite.outcome == 'failure')
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: cypress-artifacts-node${{ matrix.node-version }}
          path: test/e2e/screenshots
