name: Lint
on: [push, pull_request]

jobs:
  lint:
    name: Node.js
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: ["14.x"]

    steps:
      - name: Checkout https://github.com/${{ github.repository }}@${{ github.ref }}
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v2
        with:
          persist-credentials: false

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@270253e01c2a0e3180b4b03cb6c54e3fa2f17527 # v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run linter
        run: npx --no-install jshint@2.12.0 .
